name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ${{matrix.config.os}}
    strategy:
      matrix:
        config:
          - os: ubuntu-latest
            bin: mdgo
          - os: windows-latest
            bin: mdgo.exe
          - os: macos-latest
            bin: mdgo
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: go build
      
    - name: Upload binary
      uses: actions/upload-artifact@v2
      with:
        name: binary
        path: ${{matrix.config.os.bin}}

    - name: Install
      run: go install
    
    - name: Test manga
      run: mdgo manga https://mangadex.org/title/37f5cce0-8070-4ada-96e5-fa24b1bd4ff9/kaguya-sama-wa-kokurasetai-tensai-tachi-no-renai-zunousen kaguya -p kaguya_chap_ -C="0,5" -a "cbz"
    
    - name: Test chapter
      run: mdgo chapter 7ff854cf-dc17-4fdd-99d4-bc8f5d623b60 -a "cbz" tmp/chapter
